### ISSUE TITLE
Single FASTA file TypeError

### ISSUE THREAD

**Issue by jjkoehorst** [BackofenLab/CRISPRidentify#12] opened 2021-12-07 14:30 UTC
When executing a single fasta file using the arguments below the following occurs:

```
python CRISPRidentify.py --file TestInput/NC_019693.fa --json_report output.json      
Traceback (most recent call last):
  File "CRISPRidentify.py", line 265, in <module>
    run_over_one_file(complete_path_file, folder_result, pickle_folder, json_folder)
TypeError: run_over_one_file() takes 3 positional arguments but 4 were given
```

It seems that the function run_over_one_file() is incorrectly called from another function and is providing too many variables?

**Comment by Alexander-Mitrofanov** [comment] 2021-12-07 15:14
Thank you for the report.

The problem is fixed now. Also, please note that --json_report will create a folder with json files not one json fle.

Best,
Alex

**Closed as completed** 2021-12-07 15:14 UTC
